AWSTemplateFormatVersion: 2010-09-09
Parameters:
  LogRetention:
    Type: Number
    Default: 7
  OrgId:
    Type: String
Resources:
  s3bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  s3policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3bucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetBucketAcl
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Resource: !GetAtt s3bucket.Arn
          - Action:
              - s3:PutObject
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Resource:
              - !Sub 'arn:aws:s3:::${s3bucket}/AWSLogs/${AWS::AccountId}/*'
              - !Sub 'arn:aws:s3:::${s3bucket}/AWSLogs/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
  logGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: !Ref LogRetention
  logGroupRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                Resource: !GetAtt logGroup.Arn
  trail:
    DependsOn:
      - s3policy
    Type: AWS::CloudTrail::Trail
    Properties:
      CloudWatchLogsLogGroupArn: !GetAtt logGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt logGroupRole.Arn
      S3BucketName: !Ref s3bucket
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
